### ISSUE TITLE
How to download teacher and student weights?

### ISSUE THREAD

**Issue by HanGuangXin** [WangYZ1608/Knowledge-Distillation-via-ND#2]
Hi, thank you for your amazing work and code. I was wondering where I can find the teacher and student weights that were used in the README?

**Comment by WangYZ1608** [comment]
For CIFAR，the download link of the teacher weights is written in the README in the CIFAR folder.
For ImageNet, the weight of the teacher model comes from torch (resnet) or timm (ViT).
For student, we have released the weight of DeiT++, which can be downloaded through Baidu Cloud, and Google Cloud will be added later. Trained weights for other student models will be released soon.

**Comment by HanGuangXin** [comment]
Thanks for your time!

**Comment by angela000** [comment]
how can i download the student weight of Resnet?
