### ISSUE TITLE
train_kd.py: error: unrecognized arguments: --norm_loss_factor 1.0

### ISSUE THREAD

**Issue by HanGuangXin** [WangYZ1608/Knowledge-Distillation-via-ND#3]
It seems the args 'norm_loss_factor' is deleted? I can not find it anywhere.
![image](https://github.com/WangYZ1608/Knowledge-Distillation-via-ND/assets/48764451/d8497b63-b618-416f-8b66-9e9f60c15caa)

**Comment by WangYZ1608** [comment]
norm_loss_factor is the naming we first used, and then replaced it with nd_loss_factor. Which file does this error perform?

**Comment by HanGuangXin** [comment]
@WangYZ1608 The training may need a update? For example, the README under folder 'ImageNet' and train.sh upder folder 'ImageNetViT'.

**Comment by WangYZ1608** [comment]
We will update all the files of ImageNet in the last two days.
