### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by HanGuangXin** [WangYZ1608/Knowledge-Distillation-via-ND#4]
File "train_kd.py", line 331, in train
    t_emb, t_logits = teacher(images)
ValueError: too many values to unpack (expected 2)

**Comment by WangYZ1608** [comment]
Officially implemented resnet or other models, you need to make a little modification to extract the embedding features. As follows：
        def _forward_impl(self, x: Tensor, embed) -> Tensor:
                # See note [TorchScript super()]
                x = self.conv1(x)
                x = self.bn1(x)
                x = self.relu(x)
                x = self.maxpool(x)
        
                x = self.layer1(x)
                x = self.layer2(x)
                x = self.layer3(x)
                x = self.layer4(x)
        
                x = self.avgpool(x)
                emb_fea = torch.flatten(x, 1)
                logits = self.fc(emb_fea)
        
                if embed:
                    return emb_fea, logits
                else:
                    return logits

**Comment by WangYZ1608** [comment]
Officially implemented resnet or other models, you need to make a little modification to extract the embedding features. As follows：
  ```
def forward_impl(self, x: Tensor, embed):
        ...
        ...
        x = self.avgpool(x)
        emb_fea = torch.flatten(x, 1)
        logits = self.fc(emb_fea)
        if embed:
            return emb_fea, logits
        else:
            return logits
```

**Comment by HanGuangXin** [comment]
Yes, I guess so.
