### ISSUE TITLE
why teacher model and student model have different operation?

### ISSUE THREAD

**Issue by HanGuangXin** [WangYZ1608/Knowledge-Distillation-via-ND#6]
When set args.distributed to Ture:
```
model = torch.nn.parallel.DistributedDataParallel(model)
teacher = torch.nn.DataParallel(teacher, device_ids=[0, 1, 2, 3, 4, 5, 6, 7])
teacher.cuda()
```

Why the student model uses torch.nn.parallel.DistributedDataParallel() but teacher model uses torch.nn.DataParallel.

**Comment by WangYZ1608** [comment]
just need to set `teacher.cuda(args.gpu)`, no need to use DP or DDP.
