### ISSUE TITLE
Could you kindly provide the training log?

### ISSUE THREAD

**Issue by HanGuangXin** [WangYZ1608/Knowledge-Distillation-via-ND#7]
I am using the KD to transfer knowledge from the ViT-Base model to ResNet18 on the ImageNet dataset by following the `ImageNet/ViT/train.sh` script. However, despite training for several epochs, the top-1 accuracy has only reached 46.2% in epoch 8, and it seems to be increasing slowly. This performance is making me concerned about the final accuracy of the model.

![image](https://github.com/WangYZ1608/Knowledge-Distillation-via-ND/assets/48764451/08419f4b-d34a-491a-a830-968bdb72d397)

**Comment by WangYZ1608** [comment]
This is the `top-1 acc on train set` for DKD++, and and your results look fine.
![DKD](https://github.com/WangYZ1608/Knowledge-Distillation-via-ND/assets/100399172/8dca6883-e1ce-482e-b512-656b6198247f)
